name: Deploy to GitHub Pages (Secondary Repo)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v3

    - name: Deploy to Pages branch of secondary repo
      run: |
        set -x  # In log chi tiết
        git config --global user.email "doicucden@gmail.com"
        git config --global user.name "GitHub Actions"

        mkdir temp-pages
        cp index.html index.css index.js temp-pages/

        cd temp-pages
        git init
        git checkout -b gh-pages
        git remote add origin https://x-access-token:${{ secrets.TRINOVAVERS }}@github.com/trinovavers/tienichtrinhhg.git
        git add .
        git commit -m "Initial deploy to gh-pages"
        git push -f origin gh-pages
